# Welcome to Jekyll!
#
# Site settings
# Personalize as variáveis abaixo conforme suas preferências
title: 0xFlagged
email: xflagged6@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # Deixe vazio se você estiver usando GitHub Pages com URL padrão
url: "https://0xflagged.github.io/0xFlagged" # Substitua pelo seu link GitHub Pages
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# Remova o tema anterior e adicione o Hacker Theme como tema remoto
theme: jekyll-theme-hacker

#plugins:
 # - jekyll-feed
 # - jekyll-readme-index
 # - jekyll-remote-theme # Necessário para suportar temas remotos

# Exclude from processing.
# As seguintes pastas ou arquivos não serão processados
# Pode personalizar conforme necessidade
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
 # - Gemfile
  #- Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

